[package]
name = "ojtpdfgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdfium-render = "0.8.17"
chrono = "0.4.34"
eframe = "0.26.2"
egui = "0.26.2"